### ISSUE TITLE
Reading LQ from Linux fails 

### ISSUE THREAD

**Issue by hansaplasst** [VernierST/labquest-examples#5]
Hi,

I'm trying to read LQ data from Linux using your Python library but I get the following error:
```
>>> from labquest import LabQuest
>>> lq = LabQuest()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/labquest/__init__.py", line 37, in __init__
    dll_version = init.load_ngio_library_get_version()
  File "/usr/local/lib/python3.8/dist-packages/labquest/labquest_init_functions.py", line 11, in load_ngio_library_get_version
    config.dll = ngio_lib.load_library() 
  File "/usr/local/lib/python3.8/dist-packages/labquest/ngio_library_functions.py", line 29, in load_library
    config.logger.debug("Name of the shared library to open: " + str(dll_name))
UnboundLocalError: local variable 'dll_name' referenced before assignment
```
Looks like some Windows library is missing. Any change I'll get this working under Linux?

**Comment by sswartley** [comment]
Hello,

The Python module for LabQuest only supports Windows 10 or macOS computers.

All the best, 

Sam
