### ISSUE TITLE
Error in raspberry pi

### ISSUE THREAD

**Issue by rdzjuanjo** [VernierST/labquest-examples#6]
when trying to run the command: 
labquest = LabQuest()

I get the following error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juanjo/.local/lib/python3.9/site-packages/labquest/__init__.py", line 37, in __init__
    dll_version = init.load_ngio_library_get_version()
  File "/home/juanjo/.local/lib/python3.9/site-packages/labquest/labquest_init_functions.py", line 11, in load_ngio_library_get_version
    config.dll = ngio_lib.load_library()
  File "/home/juanjo/.local/lib/python3.9/site-packages/labquest/ngio_library_functions.py", line 29, in load_library
    config.logger.debug("Name of the shared library to open: " + str(dll_name))
UnboundLocalError: local variable 'dll_name' referenced before assignment

I'm receiving this error message when I run the program from my raspberry pi using SSH. When trying to run the command in a pc, everything runs just fine.

**Comment by sswartley** [comment]
Hello,

The Python files for LabQuest are only compatible with a Windows 10 or macOS computer.

We do have Linux/Raspberry Pi support for our [Go Direct line of sensors with Python](https://github.com/VernierST/godirect-examples/tree/main/python).

All the best,

Sam
